# Generated by Django 4.1.3 on 2022-11-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kumgan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='category_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_transport_booking', to='kumgan.category_transport'),
        ),
    ]
